---
- hosts: remote
  become: yes
  vars:
    http_port: 8082
    domain: server2.example.com
  tasks:

    - name: apache2 listen on port 8082
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8082" state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port 8082
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8082>" state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
