---
- hosts: remote
  become: yes
  vars:
    hostnamee:
    - ansibleremote01
    - ansibleremote02

  tasks:
  - name: "update hostnames"
    hostname:
      name: "{{ item }}"
    with_items: "{{ hostnamee }}"
...
