---

Config: proxy
FRONTEND_NAME: frnt
FRONTEND_PORT: 80
TIMEOUT_CLIENT_SEC: 60
BKND_TIMEOUT_CONNECT_SEC: 10
BKND_TIMEOUT_SERVER_SEC: 100
MODE: http
BACKEND_NAME: bknd
ServerDetails:
    - BACKEND_SERVER: calofornia
      BACKEND_SERVER_IP: 54.89.62.92
    - BACKEND_SERVER: virginia
      BACKEND_SERVER_IP: 52.91.7.110

